import { useState, type FormEvent } from "react";
import { CheckCircle2 } from "lucide-react";
import { toast } from "sonner";
import { celebrateSuccess } from "../utils/successConfetti";
import { Link } from "react-router-dom";
import { api, apiErrorMessage } from "../api/client";
import { Notice } from "../components/UI";
import type { ApiEnvelope, Ticket, TicketCategory } from "../types";

const categories: TicketCategory[] = ["Billing", "Technical", "Account", "Refund", "General"];
export function NewTicketPage() {
  const [form, setForm] = useState({ subject: "", description: "", customerSelectedCategory: "" }); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [created, setCreated] = useState<Ticket | null>(null);
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(""); if (form.subject.trim().length < 3) return setError("Subject must contain at least 3 characters."); if (form.description.trim().length < 10) return setError("Description must contain at least 10 characters."); setLoading(true); try { const response = await api.post<ApiEnvelope<{ ticket: Ticket }>>("/api/tickets", { subject: form.subject.trim(), description: form.description.trim(), ...(form.customerSelectedCategory ? { customerSelectedCategory: form.customerSelectedCategory } : {}) }); setCreated(response.data.data.ticket); setForm({ subject: "", description: "", customerSelectedCategory: "" }); toast.success(`Ticket ${response.data.data.ticket.ticketNumber} created.`, { id: `ticket-created-${response.data.data.ticket._id}` }); celebrateSuccess(); } catch (requestError) { const message = apiErrorMessage(requestError); setError(message); toast.error(message, { id: "ticket-create-error" }); } finally { setLoading(false); } };
  if (created) return <div className="success-card"><div className="success-check"><CheckCircle2 size={27} /></div><span className="eyebrow">Ticket submitted</span><h1>We’ve received your request.</h1><p>Your ticket number is <strong>{created.ticketNumber}</strong>. You can follow its progress and message support from the ticket page.</p><div><Link className="button primary" to={`/customer/tickets/${created._id}`}>View ticket</Link><button className="button secondary" onClick={() => setCreated(null)}>Create another</button></div></div>;
  return <div className="page-stack narrow-page"><header className="page-header"><div><span className="eyebrow">New request</span><h1>Create a support ticket</h1><p>Tell us what happened. AI will suggest a triage, and a human agent will review it.</p></div></header><section className="panel form-panel">{error && <Notice type="error">{error}</Notice>}<form className="form-stack" onSubmit={submit}><label>Subject<span className="field-help">A short title for your request</span><input value={form.subject} onChange={(event) => setForm({ ...form, subject: event.target.value })} required maxLength={150} placeholder="e.g. I can’t access my account" /></label><label>Category <span className="optional">Optional</span><select value={form.customerSelectedCategory} onChange={(event) => setForm({ ...form, customerSelectedCategory: event.target.value })}><option value="">Let the support team decide</option>{categories.map((category) => <option key={category}>{category}</option>)}</select></label><label>Description<span className="field-help">Include any details that will help us investigate</span><textarea rows={8} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} required maxLength={5000} placeholder="Describe the issue, what you expected, and what you already tried…" /></label><div className="form-actions"><Link className="button secondary" to="/customer/tickets">Cancel</Link><button className="button primary" disabled={loading}>{loading ? "Submitting…" : "Submit ticket"}</button></div></form></section></div>;
}
